apiVersion: v1
kind: Service
metadata:
  name: leadmind-service
  namespace: leadmind
spec:
  type: ClusterIP
  selector:
    app: leadmind-insight
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
